
// block_parent_id automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BlockParentId struct {
    Type string `json:"type"`
    BlockId string `json:"block_id"`
}

