
// block automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Block struct {
    Object string `json:"object"`
    Id string `json:"id"`
    Parent *Page `json:"parent"`
    CreatedTime string `json:"created_time"`
    LastEditedTime string `json:"last_edited_time"`
    CreatedBy *User `json:"created_by"`
    LastEditedBy *User `json:"last_edited_by"`
    HasChildren bool `json:"has_children"`
    InTrash bool `json:"in_trash"`
    Type string `json:"type"`
}
