
// block_link_preview automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BlockLinkPreview struct {
    LinkPreview *LinkPreview `json:"link_preview"`
}

