
// bookmark automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Bookmark struct {
    Caption []RichText `json:"caption"`
    Url string `json:"url"`
}

