
// bulleted_list_item automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BulletedListItem struct {
    RichText []BulletedListItem `json:"rich_text"`
    Color string `json:"color"`
    Children []Block `json:"children"`
}

