
// callout automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Callout struct {
    RichText []RichText `json:"rich_text"`
    Icon *Icon `json:"icon"`
    Color string `json:"color"`
}

