
// code automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Code struct {
    Caption []RichText `json:"caption"`
    RichText []RichText `json:"rich_text"`
    Language string `json:"language"`
}

