
// comment automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Comment struct {
    Parent *PageId `json:"parent"`
    DiscussionId string `json:"discussion_id"`
    RichText *RichText `json:"rich_text"`
}
