
// database_title automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type DatabaseTitle struct {
    Type string `json:"type"`
    Text string `json:"text"`
    Annotations *DatabaseAnnotations `json:"annotations"`
    PlainText string `json:"plain_text"`
    Href string `json:"href"`
}

