
// database_parent_id automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type DatabaseParentId struct {
    Type string `json:"type"`
    DatabaseId string `json:"database_id"`
}

