
// DatabasesTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type DatabasesTag struct {
    internal *sdkgen.TagAbstract
}



// Get 
func (client *DatabasesTag) Get(databaseId string) (Database, error) {
    pathParams := make(map[string]interface{})
    pathParams["database_id"] = databaseId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v1/databases/:database_id", pathParams))
    if err != nil {
        return Database{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Database{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Database{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Database{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response Database
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return Database{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return Database{}, errors.New("the server returned an unknown status code")
    }
}



func NewDatabasesTag(httpClient *http.Client, parser *sdkgen.Parser) *DatabasesTag {
	return &DatabasesTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
