
// database_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type DatabaseText struct {
    Content string `json:"content"`
    Link string `json:"link"`
}

