
// emoji_icon automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type EmojiIcon struct {
    Type string `json:"type"`
    Emoji string `json:"emoji"`
}

