
// error automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Error struct {
    Code string `json:"code"`
    Message string `json:"message"`
}

