
// external_icon automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ExternalIcon struct {
    Type string `json:"type"`
    External *ExternalObject `json:"external"`
}

