
// file automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type File struct {
    Url string `json:"url"`
    ExpiryTime string `json:"expiry_time"`
}

