
// file automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type File struct {
    Caption []RichText `json:"caption"`
    File *FileObject `json:"file"`
    Name string `json:"name"`
}

