
// file_icon automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type FileIcon struct {
    Type string `json:"type"`
    File *File `json:"file"`
}

