
// heading automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Heading struct {
    RichText []RichText `json:"rich_text"`
    Color string `json:"color"`
    IsToggleable bool `json:"is_toggleable"`
}

