
// page_parent_id automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PageParentId struct {
    Type string `json:"type"`
    PageId string `json:"page_id"`
}

