
// page automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type Page struct {
    Object string `json:"object"`
    Id string `json:"id"`
    CreatedTime time.Time `json:"created_time"`
    LastEditedTime time.Time `json:"last_edited_time"`
    CreatedBy *User `json:"created_by"`
    LastEditedBy *User `json:"last_edited_by"`
    Cover string `json:"cover"`
    Icon string `json:"icon"`
    Parent string `json:"parent"`
    InTrash bool `json:"in_trash"`
    Properties map[string]any `json:"properties"`
}
