
// page automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Page struct {
    Object string `json:"object"`
    Id string `json:"id"`
    CreatedTime string `json:"created_time"`
    LastEditedTime string `json:"last_edited_time"`
    CreatedBy *User `json:"created_by"`
    LastEditedBy *User `json:"last_edited_by"`
    Cover *FileObject `json:"cover"`
    Icon *Icon `json:"icon"`
    InTrash bool `json:"in_trash"`
    Properties map[string]any `json:"properties"`
    Parent *ParentId `json:"parent"`
    Url string `json:"url"`
    PublicUrl string `json:"public_url"`
}

