
// paragraph automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Paragraph struct {
    RichText []RichText `json:"rich_text"`
    Color string `json:"color"`
    Children []Block `json:"children"`
}

