
// pdf automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PDF struct {
    Caption []RichText `json:"caption"`
    Type string `json:"type"`
}

