
// pdf_external automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PDFExternal struct {
    Caption []RichText `json:"caption"`
    Type string `json:"type"`
    External *ExternalObject `json:"external"`
}

