
// pdf_file automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PDFFile struct {
    Caption []RichText `json:"caption"`
    Type string `json:"type"`
    File *FileObject `json:"file"`
}

