
// rich_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type RichText struct {
    Type string `json:"type"`
    Annotations *RichTextAnnotation `json:"annotations"`
    PlainText string `json:"plain_text"`
    Href string `json:"href"`
}

