
// rich_text_annotation automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type RichTextAnnotation struct {
    Bold bool `json:"bold"`
    Italic bool `json:"italic"`
    Strikethrough bool `json:"strikethrough"`
    Underline bool `json:"underline"`
    Code bool `json:"code"`
    Color string `json:"color"`
}
