
// rich_text_equation automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type RichTextEquation struct {
    Type string `json:"type"`
    Annotations *RichTextAnnotation `json:"annotations"`
    PlainText string `json:"plain_text"`
    Href string `json:"href"`
    Equation *Equation `json:"equation"`
}

