
// UserTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type UserTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Returns a paginated list of Users for the workspace. The response may contain fewer than page_size of results.
func (client *UserTag) GetAll(startCursor string, pageSize int) (UserCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["start_cursor"] = startCursor
    queryParams["page_size"] = pageSize

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v1/users", pathParams))
    if err != nil {
        return UserCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return UserCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return UserCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return UserCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response UserCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return UserCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return UserCollection{}, errors.New("the server returned an unknown status code")
    }
}

// Get 
func (client *UserTag) Get(userId string) (User, error) {
    pathParams := make(map[string]interface{})
    pathParams["user_id"] = userId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v1/users/:user_id", pathParams))
    if err != nil {
        return User{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return User{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return User{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return User{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response User
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return User{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return User{}, errors.New("the server returned an unknown status code")
    }
}



func NewUserTag(httpClient *http.Client, parser *sdkgen.Parser) *UserTag {
	return &UserTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
