
// user_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type UserCollection struct {
    Results []User `json:"results"`
    NextCursor string `json:"next_cursor"`
    HasMore bool `json:"has_more"`
}

