
// user automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type User struct {
    Object string `json:"object"`
    Id string `json:"id"`
    Type string `json:"type"`
    Person *Person `json:"person"`
    Name string `json:"name"`
    AvatarUrl string `json:"avatar_url"`
}

