
// workspace_parent_id automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type WorkspaceParentId struct {
    Type string `json:"type"`
    Workspace bool `json:"workspace"`
}

